### ISSUE TITLE
stable/v1.22.6无法下载，git上没有这个版本

### ISSUE THREAD

**Issue by bbll29** [XianyuTech/aspectd#100]
![image](https://user-images.githubusercontent.com/3722501/109143222-bdec9700-779a-11eb-90ca-6e55db4d1856.png)
下载直接报错，git上没有这个版本，应该怎么处理，才能下载1.22.6版本呢？

**Comment by bbll29** [comment]
@kangwang1988 能帮忙回答下吗

**Comment by GvcZhang** [comment]
我看 SDK 中是有的
![image](https://user-images.githubusercontent.com/45255699/109442809-14e0bd80-7a74-11eb-9e3b-29e6773c7b00.png)
然后查看依赖的更新：
![image](https://user-images.githubusercontent.com/45255699/109443087-a2bca880-7a74-11eb-9b1c-78a69a4baa36.png)

看起来继承方式上没有变化，你可以再试试，是在不行，你就把 sdk 下载下来，本地依赖一下也可以

**Comment by cuikangyuan** [comment]
这个仓库是被删除了吗
alibaba-flutter/sdk

**Comment by kangwang1988** [comment]
> 这个仓库是被删除了吗
> alibaba-flutter/sdk

被重命名了，不过不影响的，github重定向了。
