### ISSUE TITLE
Index issue when trying to apply patch

### ISSUE THREAD

**Issue by shero1111** [XianyuTech/aspectd#103]
When trying to apply patch with 
`git apply --3way /Users/..../Desktop/aspectd-master\ 2/0001-aspectd-v1.5.4.patch `

I get: 
`error: packages/flutter_tools/lib/src/commands/build_aot.dart: does not exist in index
error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index
`

Any idea how to resolve this?

**Comment by kangwang1988** [comment]
试试1.22.4或者2.0吧

你用的太老了。
