### ISSUE TITLE
debug 状态下 flutter run  是ok 的，release 报错

### ISSUE THREAD

**Issue by JsonYuu** [XianyuTech/aspectd#104]
通过flutter run --debug --verbose 命令 是可以的，但是 使用flutter run --release --verbose 就报错，但是也生成了**frontend_server.dart.snapshot** 这个文件。
报错信息：
[+2198 ms] [+2247 ms] Unhandled exception:
[        ]            Invalid argument(s): Iterables do not have same length.
[        ]            #0      MapBase._fillMap
[        ] [        ] WithIterables (dart:collection/maps.dart:92:7)
[        ]            #1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:127:13)
[        ]            #2      Substitution.fromPairs (package:kernel/type_algebra.dart:242:13)
[        ]            #3      DirectMethodInvocation.getStaticType (package:kernel/ast.dart:3542:25)
[        ]            #4      SummaryCollector._staticDartType (package:vm
[        ] [        ] /
[        ] [        ] transformations/type_flow/summary_collector.dart:1173:12)
[        ]            #5      SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dar
[        ] [        ] t:1176:36)
[        ]            #6      SummaryCollector._makeCall (package:vm/transformations/type_flow/s
[        ] [        ] ummary_collector.dart:1080:26)
[        ]            #7      SummaryCollector.visitDirectMethodInvocation (package:vm/transformations/type_flow/summary_collector.da
[        ] [        ] r
[        ] [        ] t:1519:12)
[        ]            #8      DirectMethodInvocation.accept (package:kernel/ast.dart:3528:44)
[        ]            #9      SummaryCollector._visit (package:vm/transfo
[        ] [        ] rmations/type_flow/summary_collector.dart:853:42)
[        ]            #10     SummaryCollector.visit
[        ] [        ] R
[        ] [        ] eturnStatement (package:vm/transformations/type_flow/summary_collector.dart
[        ] [        ] :2058:37)
[        ]            #11     ReturnStatement.accept (package:kernel/ast
[        ] [        ] .dart:6541:43)
[        ]            #12     SummaryCollector._visit (package:vm/t
[        ] [        ] ransformations/type_flow/summary_collector.dart:853:42)
[        ]            #13     List.forEach (dart:core-patch/growable_array.dart:313:8)
[        ]            #14     SummaryCollector.visitBlock (package:vm/transf
[        ] [        ] ormations/type_flow/summary_collector.dart:1923:21)
[        ]            #15     Block.accept (package
[        ] [        ] :
[        ] [        ] kernel/ast.dart:5873:43)
[        ]            #16     SummaryCollector._visit (package:vm/transf
[        ] [        ] ormations/type_flow/summary_collector.dart:853:42)
[        ]            #17     Summ
[        ] [        ] aryCollector.createSummary (package:vm/transformations/type_fl
[        ] [        ] ow/summary_collector.dart:758:9)
[        ]            #18     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1451:5
[        ] [        ] 2
[        ] [        ] )
[        ]            #19     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:287:42)
[        ]            #20     _DirectInvocation.process (p
[        ] [        ] a
[        ] [        ] ckage:vm/transformations/type_flow/analysis.dart:212:14)
[        ]            #21     _WorkList.processInvocation (p
[        ] [        ] ackage:vm/transformations/type_flow/analysis.dart:1347:32)
[        ]            #22     _Dispatchabl
[        ] [        ] eInvocation.process.<anonymous closure> (package:vm/transformations/type_f
[        ] [        ] low/analysis.dart:437:44)
[        ]            #23     _LinkedHashMapMixin.forEach (dart:co
[        ] [        ] llection-patch/compact_hash.dart:377:8)
[        ]            #24     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:412:12)
[        ]            #25     _WorkList.processInvocation (package
[        ] [        ] :vm/transformations/type_flow/analysis.dart:1347:32)
[        ]            #26     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1581:23)
[        ]            #27     Call.apply (package:vm/transformations/type_flow
[        ] [        ] /summary.dart:265:31)
[        ]            #28     Summary.apply (package:vm/transformations/type_flow/summary.dart:702:33)
[        ]            #29     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
[        ]            #30     _DirectInvocation.process (package:vm/transformations/ty
[        ] [        ] pe_flow/analysis.dart:212:14)
[        ]            #31     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
[        ]            #32     _DispatchableInvocation.process.
[        ] [        ] <anonymous closure> (package:vm/transformations/type_flow/analysis.dart:437:44)
[        ]            #33     _LinkedHashMapMixin.forEach (dart:collection-patch/compact
[        ] [        ] _hash.dart:377:8)
[        ]            #34     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:412:12)
[        ]            #35     _WorkList.pr
[        ] [        ] ocessInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
[        ]            #36     TypeFlowAnalysis.applyCall (package:vm/t
[        ] [        ] ransformations/type_flow/analysis.dart:1581:23)
[        ]            #37     Call.apply (package:vm/tr
[        ] [        ] ansformations/type_flow/summary.dart:265:31)
[        ]            #38     Summary.apply (pac
[        ] [        ] kage:vm/transformations/type_flow/summary.dart:702:33)
[        ]            #39     _DirectInvocation._processFunction (package:vm/transformations/type_
[        ] [        ] flow/analysis.dart:296:24)
[        ]            #40     _DirectInvocation.process (package:vm/
[        ] [        ] transformations/type_flow/analysis.dart:212:14)
[        ]            #41     _WorkList.proces
[        ] [        ] sInvocation (package:vm/transformations/type_flow/analysis.dart:1347:
[        ] [        ] 32)
[        ]            #42     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/typ
[        ] [        ] e_flow/analysis.dart:437:44)
[        ]            #43     _LinkedHa
[        ] [        ] shMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ]            #44     _DispatchableInvocation.process (package:v
[        ] [        ] m/transformations/type_flow/analysis.dart:412:12)
[        ]            #45     _WorkList.
[        ] [        ] processInvocation (package:vm/transformations/type_flow/analysis.da
[        ] [        ] rt:1347:32)
[        ]            #46     _WorkList.process (package:vm/transformations/t
[        ] [        ] ype_flow/analysis.dart:1290:7)
[        ]            #47     TypeFlo
[        ] [        ] wAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1469:14)
[        ]            #48     transformComponent (package:
[        ] [        ] vm/transformations/type_flow/transformer.dart:78:20)
[        ]            #49     runG
[        ] [        ] lobalTransformations (package:vm/kernel_front_end.dart:501:5)
[        ]            #50     compileToKernel (package:vm/kernel_front_end.dar
[        ] [        ] t:392:11)
[        ]            <asynchronous suspension>
[        ]            #51     FrontendCompiler.compile.
[        ] [        ] <anonymous closure> (package:frontend_server/frontend_server.dart:542
[        ] [        ] :54)
[        ]            #52     new Future.<anonymous closure> (dart:async/future.dart:175:37)
[        ]            #53
[        ] [        ]  _rootRun (dart:async/zone.dart:1182:47)
[        ]            #54     _CustomZ
[        ] [        ] one.run (dart:async/zone.dart:1093:19)
[        ]            #55     _CustomZone.runGuarded (da
[        ] [        ] rt:async/zone.dart:997:7)
[        ]            #56     _CustomZone.bindCallbackGuarded.<anonym
[        ] [        ] ous closure> (dart:async/zone.dart:1037:23)
[        ]            #57     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #58     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #59     _CustomZone.bindCa
[        ] [        ] llback.<anonymous closure> (dart:async/zone.dart:1021:23)
[        ]            #60     Timer._createTimer.<anonymous c
[        ] [        ] losure> (dart:async-patch/timer_patch.dart:18:15)
[        ]            #61     _Timer._runTi
[        ] [        ] mers (dart:isolate-patch/timer_impl.dart:397:19)
[        ]            #62     _Timer._handleMes
[        ] [        ] sage (dart:isolate-patch/timer_impl.dart:428:5)
[        ]            #63     _RawReceivePortI
[        ] [        ] mpl._handleMessage (dart:isolate-patch/isolat
[        ] [        ] e_patch.dart:168:12)
[  +64 ms] [  +90 ms] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +8 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.buildImpl (package:flutter_tools/src/build_system/targets/common.dart:275:7)
[        ]            <asynchronous suspension>
[        ]            #1      AspectdHook.runBuildDillCommand (package:flutter_tools/src/aspectd.dart:196:33)
[        ]            #2      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:199:27)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #4      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #11     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #12     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[  +94 ms] [  +10 ms] "flutter assemble" took 36,925ms.
[        ] [   +5 ms]
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #42     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #43     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #51     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #52     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #53     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ]            #54     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ]            #55     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ]            #56     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ]            #57     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ]            #58     Future._completeError (dart:async/future_impl.dart:537:5)
[        ]            #59     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ]            #60     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart)
[        ]            #61     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #62     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ]            #63     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ]            #64     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ]            #65     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ]            #66     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ]            #67     Future._completeError (dart:async/future_impl.dart:537:5)
[        ]            #68     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ]            #69     AspectdHook.runBuildDillCommand (package:flutter_tools/src/aspectd.dart)
[        ]            #70     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #71     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ]            #72     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ]            #73     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ]            #74     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ]            #75     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ]            #76     Future._completeError (dart:async/future_impl.dart:537:5)
[        ]            #77     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ]            #78     KernelSnapshot.buildImpl (package:flutter_tools/src/build_system/targets/common.dart)
[        ]            #79     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #80     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #81     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #82     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #83     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #84     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #85     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #86     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #87     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[        ]            #88     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #89     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #90     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #91     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #92     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #93     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #94     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #95     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #96     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #97     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #98     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #99     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #100    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #101    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #102    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\AndroidStudio\flutter_sdk\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'C:\AndroidStudio\flutter_sdk\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 39s

![image](https://user-images.githubusercontent.com/20380136/111100696-446aec00-8583-11eb-9924-7a6059bd0a87.png)

@kangwang1988 麻烦看下，谢谢

**Comment by fightcoder** [comment]
这个问题之前我已经提pr解决了，1.17.5后分支又被改回来了...你用master分支，我看了下这里是好的.

**Comment by JsonYuu** [comment]
> 这个问题之前我已经提pr解决了，1.17.5后分支又被改回来了...你用master分支，我看了下这里是好的.

我看master 分支 是已经适配 flutter 2.0  版本了，我本地flutter sdk 才v1.22.1 版本，这个 通用吗？
@fightcoder @kangwang1988

**Comment by JsonYuu** [comment]
> > 这个问题之前我已经提pr解决了，1.17.5后分支又被改回来了...你用master分支，我看了下这里是好的.
> 
> 我看master 分支 是已经适配 flutter 2.0 版本了，我本地flutter sdk 才v1.22.1 版本，这个 通用吗？
> @fightcoder @kangwang1988

使用1.22.5 版本的 可以
