### ISSUE TITLE
flutter 2.0.4 用aspectd 1.0.6 报错

### ISSUE THREAD

**Issue by lancexin** [XianyuTech/aspectd#110]
flutter2 % git apply --3way ~/Downloads/aspectd-1.0.6/0001-aspectd.patch
error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index
 flutter2 %

**Comment by JsonYuu** [comment]
> flutter2 % git apply --3way ~/Downloads/aspectd-1.0.6/0001-aspectd.patch
> error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index
> flutter2 %

怎么解决的

**Comment by lancexin** [comment]
> > flutter2 % git apply --3way ~/Downloads/aspectd-1.0.6/0001-aspectd.patch
> > error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index
> > flutter2 %
> 
> 怎么解决的

git checkout v2.0.0 然后在执行就解决了，貌似只支持到2.0.0
