### ISSUE TITLE
aspectd_impl 里面的代码在每次启动后不自动编译

### ISSUE THREAD

**Issue by lancexin** [XianyuTech/aspectd#111]
在修改了aspectd_impl 里面的代码后，重启启动程序，发现还是以前老的代码
一定要把项目里面的 .dart_tools 和 .packages目录删除，然后再次启动新代码才生效

**Comment by yubaokang** [comment]
我发现改了代码，重新执行 flutter run --debug --verbose 代码没有生效。请问你解决了吗？

**Comment by lancexin** [comment]
1.如果只是修改aspectd_impl里面的代码然后重新执行flutter run --debug --verbose是不生效的，这应该和编译机制有关系
2.如果同时修改了主项目代码和aspectd_impl的代码是生效的
3.偶然出现引入了新的包，再重新编译发现包未发现的问题，考虑是aspectd_impl没有及时编译的原因，将aspectd_impl里的.dart_tools 和 .packages目录删除再重新编译解决
