### ISSUE TITLE
constructor arguments that have default value will lost after call hook

### ISSUE THREAD

**Issue by ameryzhu** [XianyuTech/aspectd#88]
`class A {
  bool show;

  A({this.show = false});
}

void main() {
  A a = A();
  if (a.show) {
    print('show');
  }
}

  @Call("package:example/main.dart", "A", "+A")
  @pragma("vm:entry-point")
  static dynamic hookMethod(PointCut pointcut) {
    print('[KWLM1]: Before A! ');
    dynamic object = pointcut.proceed();
    print('[KWLM1]: After A! ');
    return object;
  }
`

flutter doctor 信息：

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (3 available)

• No issues found!

A null pointer exception would be threw out.

**Comment by kangwang1988** [comment]
<img width="1671" alt="Screen Shot 2021-04-10 at 2 45 02 PM" src="https://user-images.githubusercontent.com/817851/114261110-68e3a800-9a0b-11eb-8a18-60c1227f5ba8.png">

https://github.com/XianyuTech/aspectd/issues/86
这个解决后，此问题应该一并消失了。
