### ISSUE TITLE
Video Tutorial would be helpful for using aspectd

### ISSUE THREAD

**Issue by shinewanna** [XianyuTech/aspectd#95]
I have to do these steps for use aspectd?
![Screen Shot 2021-01-28 at 3 16 47 PM](https://user-images.githubusercontent.com/39454969/106112646-eb362d00-617b-11eb-9be8-d8ffc333150c.png)
Installing aspectd: ^0.9.8 in pubspec.yaml is not enough to go through?
I'm confuse.

**Comment by GvcZhang** [comment]
You can try it multi times, you will familiar with it. Of course, you can upload your Video Tutorial, I think the author no time to maintain this project.

**Comment by kangwang1988** [comment]
I think README.md, UPGRADE.md and example embedded are enough.

Besides, It's very easy to keep up with the latest flutter stable versions.
