### ISSUE TITLE
Inject 如何使用？

### ISSUE THREAD

**Issue by GvcZhang** [XianyuTech/aspectd#97]
Hi All，

我想在如下的一个方法中插入一段代码，如代码中注释所示

```dart
void _handleTabControllerTick() {
    if (_controller.index != _currentIndex) {
      _currentIndex = _controller.index;
     //想要在这个位置插入一段代码
      if (widget.isScrollable)
        _scrollToCurrentIndex();
    }
    setState(() {
      // Rebuild the tabs after a (potentially animated) index change
      // has completed.
    });
  }
```
因为这里的 _controller 和 _currentIndex 是 private 的，所以我想使用 Inject，在使用的时候发现必须要设置 lineNum，否则就会出错，因为 hook 的代码在未来可能会发生变化，现在有如下问题：

1. 不使用 lineNum 是否可行？
2. 有没有其他方式来做这个功能？
3. 如何能拿到 _controller 和 _currentIndex，因为如果能拿到这两个值，我就可以判断是否需要进行 hook

**Comment by kangwang1988** [comment]
> Hi All，
> 
> 我想在如下的一个方法中插入一段代码，如代码中注释所示
> 
> ```dart
> void _handleTabControllerTick() {
>     if (_controller.index != _currentIndex) {
>       _currentIndex = _controller.index;
>      //想要在这个位置插入一段代码
>       if (widget.isScrollable)
>         _scrollToCurrentIndex();
>     }
>     setState(() {
>       // Rebuild the tabs after a (potentially animated) index change
>       // has completed.
>     });
>   }
> ```
> 
> 因为这里的 _controller 和 _currentIndex 是 private 的，所以我想使用 Inject，在使用的时候发现必须要设置 lineNum，否则就会出错，因为 hook 的代码在未来可能会发生变化，现在有如下问题：
> 
> 1. 不使用 lineNum 是否可行？
> 2. 有没有其他方式来做这个功能？
> 3. 如何能拿到 _controller 和 _currentIndex，因为如果能拿到这两个值，我就可以判断是否需要进行 hook

1. 必须使用lineNum
inject内部的逻辑其实是一行一行地遍历ASTStatement，然后看插入到哪里。
3. 理论上是可以的，主要是一个内部变量的获取，你需要考虑两个问题
a. aop_impl.dart中添加同样名称的变量（_currentIndex），保证你可以正常编译aop_impl.dart
b. 调试aspectd，将其对于_currentIndex，变成对于this._currentIndex这种的访问。我印象中是支持的。

**Comment by FloydP** [comment]
@GvcZhang  HI，现在你是能否在 Inject 拿到 _controller 和 _currentIndex呢，我有类似的需求，能否说下应该如何实现呢？

**Comment by GvcZhang** [comment]
> @GvcZhang HI，现在你是能否在 Inject 拿到 _controller 和 _currentIndex呢，我有类似的需求，能否说下应该如何实现呢？

这里是我的做法，使用 Execute，然后去到到 TabController，进而获取到 index，希望对你有帮助。
```
  @Execute("package:flutter/src/material/tabs.dart", "_TabBarState",
      "-_handleTabControllerTick")
  // @Inject("package:flutter/src/material/tabs.dart", "_TabBarState",
  //         "-_handleTabControllerTick",lineNum: 987)
  @pragma("vm:entry-point")
  void _trackTabViewScreen(PointCut pointCut) {
    dynamic target = pointCut.target;
    dynamic widget = target.widget;
    final TabController controller =
        widget.controller ?? DefaultTabController.of(target.context);
    pointCut.proceed();
    print("=======${controller.index}");
  
  }
```

**Comment by FloydP** [comment]
> > @GvcZhang HI，现在你是能否在 Inject 拿到 _controller 和 _currentIndex呢，我有类似的需求，能否说下应该如何实现呢？
> 
> 这里是我的做法，使用 Execute，然后去到到 TabController，进而获取到 index，希望对你有帮助。
> 
> ```
>   @Execute("package:flutter/src/material/tabs.dart", "_TabBarState",
>       "-_handleTabControllerTick")
>   // @Inject("package:flutter/src/material/tabs.dart", "_TabBarState",
>   //         "-_handleTabControllerTick",lineNum: 987)
>   @pragma("vm:entry-point")
>   void _trackTabViewScreen(PointCut pointCut) {
>     dynamic target = pointCut.target;
>     dynamic widget = target.widget;
>     final TabController controller =
>         widget.controller ?? DefaultTabController.of(target.context);
>     pointCut.proceed();
>     print("=======${controller.index}");
>   
>   }
> ```

@GvcZhang 这对我有帮助，十分感谢~
