### ISSUE TITLE
Call GestureDetector 构造方法 报错

### ISSUE THREAD

**Issue by kelciej** [XianyuTech/aspectd#98]
1.22.6版本，1.22.2版本都试过了。
能够顺利地跑demo。
但是Call以下构造方法会报错。

以前试过1.12.13版本的，下述方法可执行
>` 
    
    @Call("package:flutter/src/widgets/gesture_detector.dart", "GestureDetector", "+GestureDetector")
    
    @pragma("vm:entry-point")

    static dynamic hookGestureDetector(PointCut pointcut) {
 
    dynamic obj = pointcut.proceed();

    print('[KWLM4]: GestureDetector named constructor!');

    return obj;
  }
`

报错 

Unhandled exception:                                                    
Crash when compiling null,                                              
at character offset null:                                               
NoSuchMethodError: The getter 'line' was called on null.                
Receiver: null                                                          
Tried calling: line                                                     
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)    
#1      _WidgetCallSiteTransformer._constructLocation (package:kernel/transformations/track_widget_constructor_locations.dart:164:59)
#2      _WidgetCallSiteTransformer._computeLocation (package:kernel/transformations/track_widget_constructor_locations.dart:272:30)
#3      _WidgetCallSiteTransformer._addLocationArgument (package:kernel/transformations/track_widget_constructor_locations.dart:223:7)
#4      _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:238:5)
#5      ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#6      MapEntry.transformChildren (package:kernel/ast.dart:5504:21)    
#7      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#8      TreeVisitor.visitMapEntry (package:kernel/visitor.dart:265:37)  
#9      MapEntry.accept (package:kernel/ast.dart:5491:38)               
#10     transformList (package:kernel/ast.dart:9699:27)                 
#11     MapLiteral.transformChildren (package:kernel/ast.dart:5454:5)   
#12     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#13     TreeVisitor.defaultExpression (package:kernel/visitor.dart:144:43)
#14     TreeVisitor.visitMapLiteral (package:kernel/visitor.dart:186:41)
#15     MapLiteral.accept (package:kernel/ast.dart:5441:44)             
#16     transformList (package:kernel/ast.dart:9699:27)                 
#17     Arguments.transformChildren (package:kernel/ast.dart:3813:5)    
#18     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#19     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#20     Arguments.accept (package:kernel/ast.dart:3803:38)              
#21     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#22     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#23     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#24     transformList (package:kernel/ast.dart:9699:27)                 
#25     Arguments.transformChildren (package:kernel/ast.dart:3813:5)    
#26     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#27     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#28     Arguments.accept (package:kernel/ast.dart:3803:38)              
#29     StaticInvocation.transformChildren (package:kernel/ast.dart:4149:29)
#30     _WidgetCallSiteTransformer.visitStaticInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:202:10)
#31     StaticInvocation.accept (package:kernel/ast.dart:4138:44)       
#32     transformList (package:kernel/ast.dart:9699:27)                 
#33     ListLiteral.transformChildren (package:kernel/ast.dart:5353:5)  
#34     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#35     TreeVisitor.defaultExpression (package:kernel/visitor.dart:144:43)
#36     TreeVisitor.visitListLiteral (package:kernel/visitor.dart:184:43)
#37     ListLiteral.accept (package:kernel/ast.dart:5342:44)            
#38     NamedExpression.transformChildren (package:kernel/ast.dart:3871:21)
#39     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#40     TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:262:51)
#41     NamedExpression.accept (package:kernel/ast.dart:3863:38)        
#42     transformList (package:kernel/ast.dart:9699:27)                 
#43     Arguments.transformChildren (package:kernel/ast.dart:3814:5)    
#44     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#45     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#46     Arguments.accept (package:kernel/ast.dart:3803:38)              
#47     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#48     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#49     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#50     NamedExpression.transformChildren (package:kernel/ast.dart:3871:21)
#51     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#52     TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:262:51)
#53     NamedExpression.accept (package:kernel/ast.dart:3863:38)        
#54     transformList (package:kernel/ast.dart:9699:27)                 
#55     Arguments.transformChildren (package:kernel/ast.dart:3814:5)    
#56     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#57     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#58     Arguments.accept (package:kernel/ast.dart:3803:38)              
#59     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#60     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#61     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#62     NamedExpression.transformChildren (package:kernel/ast.dart:3871:21)
#63     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#64     TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:262:51)
#65     NamedExpression.accept (package:kernel/ast.dart:3863:38)        
#66     transformList (package:kernel/ast.dart:9699:27)                 
#67     Arguments.transformChildren (package:kernel/ast.dart:3814:5)    
#68     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#69     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#70     Arguments.accept (package:kernel/ast.dart:3803:38)              
#71     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#72     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#73     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#74     ReturnStatement.transformChildren (package:kernel/ast.dart:6551:31)
#75     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#76     TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#77     TreeVisitor.visitReturnStatement (package:kernel/visitor.dart:220:51)
#78     ReturnStatement.accept (package:kernel/ast.dart:6541:43)        
#79     transformList (package:kernel/ast.dart:9699:27)                 
#80     Block.transformChildren (package:kernel/ast.dart:5881:5)        
#81     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#82     TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#83     TreeVisitor.visitBlock (package:kernel/visitor.dart:206:31)     
#84     Block.accept (package:kernel/ast.dart:5873:43)                  
#85     FunctionNode.transformChildren (package:kernel/ast.dart:2948:19)
#86     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#87     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:260:45)
#88     FunctionNode.accept (package:kernel/ast.dart:2932:38)           
#89     Procedure.transformChildren (package:kernel/ast.dart:2436:27)   
#90     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#91     _WidgetCallSiteTransformer.visitProcedure (package:kernel/transformations/track_widget_constructor_locations.dart:193:12)
#92     Procedure.accept (package:kernel/ast.dart:2423:40)              
#93     transformList (package:kernel/ast.dart:9699:27)                 
#94     Class.transformChildren (package:kernel/ast.dart:1428:5)        
#95     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#96     TreeVisitor.visitClass (package:kernel/visitor.dart:239:31)     
#97     Class.accept (package:kernel/ast.dart:1379:38)                  
#98     transformList (package:kernel/ast.dart:9699:27)                 
#99     Library.transformChildren (package:kernel/ast.dart:625:5)       
#100    WidgetCreatorTracker.transform (package:kernel/transformations/track_widget_constructor_locations.dart:504:15)
#101    FlutterTarget.performPreConstantEvaluationTransformations (package:vm/target/flutter.dart:82:22)
#102    KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1093:19)
#103    KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:390:7)
<asynchronous suspension>                                               
#104    KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#105    withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#106    KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
#107    generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>                                               
#108    generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#109    withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#110    generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#111    kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:61:35)
#112    CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>                                               
#113    CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#114    CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#115    new Future.sync (dart:async/future.dart:223:31)                 
#116    CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#117    _rootRun (dart:async/zone.dart:1190:13)                         
#118    _CustomZone.run (dart:async/zone.dart:1093:19)                  
#119    _runZoned (dart:async/zone.dart:1630:10)                        
#120    runZoned (dart:async/zone.dart:1550:10)                         
#121    CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#122    CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#123    kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
#124    kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
#125    compileToKernel (package:vm/kernel_front_end.dart:381:28)       
#126    FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:542:54)
#127    new Future.<anonymous closure> (dart:async/future.dart:175:37)  
#128    _rootRun (dart:async/zone.dart:1182:47)                         
#129    _CustomZone.run (dart:async/zone.dart:1093:19)                  
#130    _CustomZone.runGuarded (dart:async/zone.dart:997:7)             
#131    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#132    _rootRun (dart:async/zone.dart:1190:13)                         
#133    _CustomZone.run (dart:async/zone.dart:1093:19)                  
#134    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#135    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#136    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)   
#137    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#138    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
                                                                        
                                                                        
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)    
#1      _WidgetCallSiteTransformer._constructLocation (package:kernel/transformations/track_widget_constructor_locations.dart:164:59)
#2      _WidgetCallSiteTransformer._computeLocation (package:kernel/transformations/track_widget_constructor_locations.dart:272:30)
#3      _WidgetCallSiteTransformer._addLocationArgument (package:kernel/transformations/track_widget_constructor_locations.dart:223:7)
#4      _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:238:5)
#5      ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#6      MapEntry.transformChildren (package:kernel/ast.dart:5504:21)    
#7      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#8      TreeVisitor.visitMapEntry (package:kernel/visitor.dart:265:37)  
#9      MapEntry.accept (package:kernel/ast.dart:5491:38)               
#10     transformList (package:kernel/ast.dart:9699:27)                 
#11     MapLiteral.transformChildren (package:kernel/ast.dart:5454:5)   
#12     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#13     TreeVisitor.defaultExpression (package:kernel/visitor.dart:144:43)
#14     TreeVisitor.visitMapLiteral (package:kernel/visitor.dart:186:41)
#15     MapLiteral.accept (package:kernel/ast.dart:5441:44)             
#16     transformList (package:kernel/ast.dart:9699:27)                 
#17     Arguments.transformChildren (package:kernel/ast.dart:3813:5)    
#18     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#19     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#20     Arguments.accept (package:kernel/ast.dart:3803:38)              
#21     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#22     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#23     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#24     transformList (package:kernel/ast.dart:9699:27)                 
#25     Arguments.transformChildren (package:kernel/ast.dart:3813:5)    
#26     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#27     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#28     Arguments.accept (package:kernel/ast.dart:3803:38)              
#29     StaticInvocation.transformChildren (package:kernel/ast.dart:4149:29)
#30     _WidgetCallSiteTransformer.visitStaticInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:202:10)
#31     StaticInvocation.accept (package:kernel/ast.dart:4138:44)       
#32     transformList (package:kernel/ast.dart:9699:27)                 
#33     ListLiteral.transformChildren (package:kernel/ast.dart:5353:5)  
#34     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#35     TreeVisitor.defaultExpression (package:kernel/visitor.dart:144:43)
#36     TreeVisitor.visitListLiteral (package:kernel/visitor.dart:184:43)
#37     ListLiteral.accept (package:kernel/ast.dart:5342:44)            
#38     NamedExpression.transformChildren (package:kernel/ast.dart:3871:21)
#39     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#40     TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:262:51)
#41     NamedExpression.accept (package:kernel/ast.dart:3863:38)        
#42     transformList (package:kernel/ast.dart:9699:27)                 
#43     Arguments.transformChildren (package:kernel/ast.dart:3814:5)    
#44     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#45     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#46     Arguments.accept (package:kernel/ast.dart:3803:38)              
#47     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#48     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#49     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#50     NamedExpression.transformChildren (package:kernel/ast.dart:3871:21)
#51     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#52     TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:262:51)
#53     NamedExpression.accept (package:kernel/ast.dart:3863:38)        
#54     transformList (package:kernel/ast.dart:9699:27)                 
#55     Arguments.transformChildren (package:kernel/ast.dart:3814:5)    
#56     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#57     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#58     Arguments.accept (package:kernel/ast.dart:3803:38)              
#59     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#60     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#61     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#62     NamedExpression.transformChildren (package:kernel/ast.dart:3871:21)
#63     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#64     TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:262:51)
#65     NamedExpression.accept (package:kernel/ast.dart:3863:38)        
#66     transformList (package:kernel/ast.dart:9699:27)                 
#67     Arguments.transformChildren (package:kernel/ast.dart:3814:5)    
#68     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#69     TreeVisitor.visitArguments (package:kernel/visitor.dart:261:39) 
#70     Arguments.accept (package:kernel/ast.dart:3803:38)              
#71     ConstructorInvocation.transformChildren (package:kernel/ast.dart:4215:29)
#72     _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:230:10)
#73     ConstructorInvocation.accept (package:kernel/ast.dart:4204:44)  
#74     ReturnStatement.transformChildren (package:kernel/ast.dart:6551:31)
#75     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#76     TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#77     TreeVisitor.visitReturnStatement (package:kernel/visitor.dart:220:51)
#78     ReturnStatement.accept (package:kernel/ast.dart:6541:43)        
#79     transformList (package:kernel/ast.dart:9699:27)                 
#80     Block.transformChildren (package:kernel/ast.dart:5881:5)        
#81     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#82     TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#83     TreeVisitor.visitBlock (package:kernel/visitor.dart:206:31)     
#84     Block.accept (package:kernel/ast.dart:5873:43)                  
#85     FunctionNode.transformChildren (package:kernel/ast.dart:2948:19)
#86     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#87     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:260:45)
#88     FunctionNode.accept (package:kernel/ast.dart:2932:38)           
#89     Procedure.transformChildren (package:kernel/ast.dart:2436:27)   
#90     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#91     _WidgetCallSiteTransformer.visitProcedure (package:kernel/transformations/track_widget_constructor_locations.dart:193:12)
#92     Procedure.accept (package:kernel/ast.dart:2423:40)              
#93     transformList (package:kernel/ast.dart:9699:27)                 
#94     Class.transformChildren (package:kernel/ast.dart:1428:5)        
#95     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#96     TreeVisitor.visitClass (package:kernel/visitor.dart:239:31)     
#97     Class.accept (package:kernel/ast.dart:1379:38)                  
#98     transformList (package:kernel/ast.dart:9699:27)                 
#99     Library.transformChildren (package:kernel/ast.dart:625:5)       
#100    WidgetCreatorTracker.transform (package:kernel/transformations/track_widget_constructor_locations.dart:504:15)
#101    FlutterTarget.performPreConstantEvaluationTransformations (package:vm/target/flutter.dart:82:22)
#102    KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1093:19)
#103    KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:390:7)
<asynchronous suspension>                                               
#104    KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#105    withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#106    KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
#107    generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>                                               
#108    generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#109    withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#110    generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#111    kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:61:35)
#112    CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>                                               
#113    CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#114    CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#115    new Future.sync (dart:async/future.dart:223:31)                 
#116    CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#117    _rootRun (dart:async/zone.dart:1190:13)                         
#118    _CustomZone.run (dart:async/zone.dart:1093:19)                  
#119    _runZoned (dart:async/zone.dart:1630:10)                        
#120    runZoned (dart:async/zone.dart:1550:10)                         
#121    CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#122    CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#123    kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
#124    kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
#125    compileToKernel (package:vm/kernel_front_end.dart:381:28)       
#126    FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:542:54)
#127    new Future.<anonymous closure> (dart:async/future.dart:175:37)  
#128    _rootRun (dart:async/zone.dart:1182:47)                         
#129    _CustomZone.run (dart:async/zone.dart:1093:19)                  
#130    _CustomZone.runGuarded (dart:async/zone.dart:997:7)             
#131    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#132    _rootRun (dart:async/zone.dart:1190:13)                         
#133    _CustomZone.run (dart:async/zone.dart:1093:19)                  
#134    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#135    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#136    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)   
#137    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#138    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by GvcZhang** [comment]
可以试试`Inject`方式，`Call`和`Excecute`不适合这种场景？

**Comment by kangwang1988** [comment]
https://github.com/XianyuTech/aspectd/issues/109

**Comment by kangwang1988** [comment]
<img width="1766" alt="Screen Shot 2021-04-10 at 3 05 16 PM" src="https://user-images.githubusercontent.com/817851/114261661-66cf1880-9a0e-11eb-852a-cfb4d54da7ab.png">
