### ISSUE TITLE
集成AspectD到自己项目，按照流程集成，过程不报错，但插桩没有生效

### ISSUE THREAD

**Issue by bbll29** [XianyuTech/aspectd#99]
![image](https://user-images.githubusercontent.com/3722501/108974911-e6a05e00-76c0-11eb-87e9-c83f0b59502a.png)
这是项目结构

![image](https://user-images.githubusercontent.com/3722501/108975060-0c2d6780-76c1-11eb-9118-04f28d2aa280.png)
这是配置文件

![image](https://user-images.githubusercontent.com/3722501/108975133-20716480-76c1-11eb-9b42-79227a6b29f0.png)
这是插桩的代码

1、之后按照文档上的1、2、3步骤执行，没有报错，也能正常按照，但插桩却没有生效，搞了几天了，换了好多种方案，完全没有头绪
2、Flutter SDK也切换成1.22.2版本，和指定的AspectD保持一致
3、设置git apply --3way path-for-aspectd-package/0001-aspectd.patch时，用的是源码中的0001-aspectd.patch

**Comment by GvcZhang** [comment]
你需要将`aspectd_impl`这个工程放在你自己 `market-flutter`这个工程的同级目录才行。

**Comment by GvcZhang** [comment]
感觉这个项目已经渐渐的不再维护了的样子。
